### ISSUE TITLE
Error: Not all tracks are grouped in "x"

### ISSUE THREAD

**Issue by andreakoelzsch** [movestore/move2_loc-to-moveStack#1]
Alex: ... Allerdings habe ich beim ersten Versuch mit der neuen move2 Movebank App folgenden Error erhalten. Als ich dann Argument Minimisation angeklickt habe, die Daten auf eine Location pro Stunde reduziert habe und den Workflow noch mal habe laufen lassen, hat dann alles funktioniert. Vielleicht weißt du ja, was passiert sein könnte.
(@annescharf FYI)

![image](https://github.com/movestore/move2_loc-to-moveStack/assets/65662928/489fb58e-28e9-4812-8b2c-342bfc8b94f1)

**Comment by annescharf** [comment]
hmm, etwas komisch da in der movebank app die daten sortiert werden... Aber da Apps dazwischen alles mögliche machen müssen, sollen wir ein paar assertions reinbauen, zB daten sortiert? duplicate timestamps?. Ich habe dies bzgl Bart mal gefragt https://gitlab.com/bartk/move2/-/issues/66. Sobald er antwortet kann ich es einbauen

Hat Alex dir gesagt mit welchen Daten das Problem aufgetaucht ist?

**Comment by andreakoelzsch** [comment]
Sieht aus wie Störche von Wolfgang: Ich sehe gerade, dass er auch den Workflow mit mir geteilt hat: 
Study: 21231406: LifeTrack White Stork SW Germany
Animals: Angela / DER AY470 (eobs 4001), Ella + / DER AU051 (eobs 3338), Kiki + / DER AN872 (eobs 3648), Nils + / DER AU058 (eobs 3335), Ronja + / DER AU004 (eobs 3926), Spiderwoman + / DER AU047 (eobs 3964)
Ich bau mal die neue move2TOmovestack App version und schau, ob es dann passt. LG

**Comment by andreakoelzsch** [comment]
@annescharf Ich realisiere erst beim Blick auf den geteilten workflow, dass die Fehlermeldung siehe oben aus der Movebank move2 App kommt. Ich hab es mal lokal nachgestellt: Der Fehler kommt bei:  mt_filter_per_interval(locs,criterion="first",unit=paste(thin_numb,thin_unit))
Es scheint, dass das ordnen nach track und time oben nicht funktioniert. ich hab es mal an der Stelle und generell zur Sicherheit auch ganz simpel mit order() hinzugefügt (wie die Fehlermeldung empfiehlt: 
locs <- locs[order(mt_track_id(locs),mt_time(locs)),]
Neue Version reich ich gleich mal ein. Keine Ahnung warum dplyr nicht zu funktionieren scheint, ist vielleicht gut, das noch rauszufinden und auch in den anderen Apps verbessern. Wenn du was Zeit dafür findest :S Danke!

**Comment by andreakoelzsch** [comment]
aber so nichtstuend kann das dplyr auch nicht sein, da die neue version dieser App (move2TOmovestack) besser funktioniert... (@annescharf )

**Comment by annescharf** [comment]
@andreakoelzsch , habs gefunden, removing duplicate timestamp code sortiert die daten um. Ich gehe nachher mal durch alle codes und passe es an.

``` r
library(move2)
library(dplyr)

mv <- movebank_download_study(21231406,individual_local_identifier=c("Angela / DER AY470 (eobs 4001)", "Ella + / DER AU051 (eobs 3338)", "Kiki + / DER AN872 (eobs 3648)"))#, "Nils + / DER AU058 (eobs 3335)", "Ronja + / DER AU004 (eobs 3926)", "Spiderwoman + / DER AU047 (eobs 3964)"))

mt_is_time_ordered(mv)
#> Error: Not all tracks are grouped in `x`.
#> ℹ The following tracks occur at multiple places in the data set: `Kiki + / DER
#>   AN872 (eobs 3648)`, `Ella + / DER AU051 (eobs 3338)`, and `Angela / DER AY470
#>   (eobs 4001)`.
#> ℹ This can be resolved resolved by ordering the data e.g.:
#>   `x[order(mt_track_id(x)),]`

mv2 <- mv[order(mt_track_id(mv),mt_time(mv)),]
mt_is_time_ordered(mv2)
#> [1] TRUE

mv3 <- mv |> dplyr::arrange(mt_track_id(mv),mt_time(mv))
mt_is_time_ordered(mv3)
#> [1] TRUE

mt_has_unique_location_time_records(mv3)
#> [1] FALSE
mv4 <- mv3 %>%
  mutate(n_na = rowSums(is.na(pick(everything())))) %>%
  arrange(n_na) %>%
  mt_filter_unique(criterion='first') 
mt_is_time_ordered(mv4)
#> Error: Not all tracks are grouped in `x`.
#> ℹ The following tracks occur at multiple places in the data set: `Angela / DER
#>   AY470 (eobs 4001)`, `Kiki + / DER AN872 (eobs 3648)`, and `Ella + / DER AU051
#>   (eobs 3338)`.
#> ℹ This can be resolved resolved by ordering the data e.g.:
#>   `x[order(mt_track_id(x)),]`
```

<sup>Created on 2023-12-21 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>
